[project]
name = "dutchmate-service"
version = "0.1.0"
description = "DUTchMate Device Core Service."
requires-python = ">=3.10"
license = "Apache-2.0"
license-files = ["LICENSE"]
authors = [{ name = "Nahit Pawar" }]
dependencies = [
  "dutchmate-core==0.1.0",
  "fastapi>=0.115",
  "uvicorn>=0.30",
]

[project.urls]
Homepage = "https://github.com/leonahi/DUTchMate"
Repository = "https://github.com/leonahi/DUTchMate"
Issues = "https://github.com/leonahi/DUTchMate/issues"

[build-system]
requires = ["uv_build>=0.11.26,<0.12"]
build-backend = "uv_build"
