"""Stable facade for normalized Device Core backend contracts."""

from dutchmate_core.backends.contracts import (
    BackendCapability,
    BackendCapabilityError,
    BackendCapabilityPolicy,
    BackendDisconnectedError,
    BackendEvent,
    BackendEventSource,
    BackendInfo,
    BackendInputError,
    BackendMode,
    BackendSnapshot,
    BackendUartSendResult,
    BackendWriteError,
    BufferOverflowEvent,
    BufferStatusEvent,
    DeviceControl,
    DeviceControlError,
    LossStatus,
    SegmentContext,
    SegmentTimestamp,
    UartIntegrity,
    UartReceiveEvent,
    UartSendCapabilityPolicy,
    UartSender,
    apply_capability_policy,
    integrity_for_backend,
)

__all__ = [
    "BackendCapability",
    "BackendCapabilityError",
    "BackendCapabilityPolicy",
    "BackendDisconnectedError",
    "BackendEvent",
    "BackendEventSource",
    "BackendInfo",
    "BackendInputError",
    "BackendMode",
    "BackendSnapshot",
    "BackendUartSendResult",
    "BufferOverflowEvent",
    "BufferStatusEvent",
    "DeviceControl",
    "DeviceControlError",
    "LossStatus",
    "BackendWriteError",
    "SegmentContext",
    "SegmentTimestamp",
    "UartIntegrity",
    "UartReceiveEvent",
    "UartSendCapabilityPolicy",
    "UartSender",
    "apply_capability_policy",
    "integrity_for_backend",
]
